/* Generated by bin2c, do not edit manually */

/* Contents of file amper.pxl */
#define amper_pxl_size 4
const unsigned char amper_pxl[4] = {
    0x45, 0x15, 0x4D, 0x00
};

/* Contents of file apost.pxl */
#define apost_pxl_size 4
const unsigned char apost_pxl[4] = {
    0x84, 0x00, 0x00, 0x00
};

/* Contents of file asterisk.pxl */
#define asterisk_pxl_size 4
const unsigned char asterisk_pxl[4] = {
    0xA2, 0x28, 0x00, 0x00
};

/* Contents of file at.pxl */
#define at_pxl_size 4
const unsigned char at_pxl[4] = {
    0x74, 0x67, 0x51, 0x80
};

/* Contents of file brace_l.pxl */
#define brace_l_pxl_size 4
const unsigned char brace_l_pxl[4] = {
    0x62, 0x20, 0x86, 0x00
};

/* Contents of file brace_r.pxl */
#define brace_r_pxl_size 4
const unsigned char brace_r_pxl[4] = {
    0xC2, 0x08, 0x8C, 0x00
};

/* Contents of file bracket_l.pxl */
#define bracket_l_pxl_size 4
const unsigned char bracket_l_pxl[4] = {
    0xC4, 0x21, 0x0C, 0x00
};

/* Contents of file bracket_r.pxl */
#define bracket_r_pxl_size 4
const unsigned char bracket_r_pxl[4] = {
    0xC2, 0x10, 0x8C, 0x00
};

/* Contents of file carat.pxl */
#define carat_pxl_size 4
const unsigned char carat_pxl[4] = {
    0x45, 0x00, 0x00, 0x00
};

/* Contents of file chev_l.pxl */
#define chev_l_pxl_size 4
const unsigned char chev_l_pxl[4] = {
    0x02, 0x20, 0x80, 0x00
};

/* Contents of file chev_r.pxl */
#define chev_r_pxl_size 4
const unsigned char chev_r_pxl[4] = {
    0x04, 0x11, 0x00, 0x00
};

/* Contents of file colon.pxl */
#define colon_pxl_size 4
const unsigned char colon_pxl[4] = {
    0x04, 0x01, 0x00, 0x00
};

/* Contents of file comma.pxl */
#define comma_pxl_size 4
const unsigned char comma_pxl[4] = {
    0x00, 0x00, 0x88, 0x00
};

/* Contents of file dash.pxl */
#define dash_pxl_size 4
const unsigned char dash_pxl[4] = {
    0x00, 0x38, 0x00, 0x00
};

/* Contents of file dollar.pxl */
#define dollar_pxl_size 4
const unsigned char dollar_pxl[4] = {
    0x7D, 0x1C, 0x5F, 0x00
};

/* Contents of file equal.pxl */
#define equal_pxl_size 4
const unsigned char equal_pxl[4] = {
    0x07, 0x81, 0xE0, 0x00
};

/* Contents of file exc.pxl */
#define exc_pxl_size 4
const unsigned char exc_pxl[4] = {
    0x84, 0x20, 0x08, 0x00
};

/* Contents of file l_a.pxl */
#define l_a_pxl_size 4
const unsigned char l_a_pxl[4] = {
    0x03, 0xA5, 0x65, 0x00
};

/* Contents of file l_b.pxl */
#define l_b_pxl_size 4
const unsigned char l_b_pxl[4] = {
    0x87, 0x25, 0x2E, 0x00
};

/* Contents of file l_c.pxl */
#define l_c_pxl_size 4
const unsigned char l_c_pxl[4] = {
    0x03, 0xA1, 0x07, 0x00
};

/* Contents of file l_d.pxl */
#define l_d_pxl_size 4
const unsigned char l_d_pxl[4] = {
    0x13, 0xA5, 0x27, 0x00
};

/* Contents of file l_e.pxl */
#define l_e_pxl_size 4
const unsigned char l_e_pxl[4] = {
    0x03, 0x3D, 0x06, 0x00
};

/* Contents of file l_f.pxl */
#define l_f_pxl_size 4
const unsigned char l_f_pxl[4] = {
    0x22, 0x38, 0x84, 0x00
};

/* Contents of file l_g.pxl */
#define l_g_pxl_size 4
const unsigned char l_g_pxl[4] = {
    0x74, 0x9C, 0x2E, 0x00
};

/* Contents of file l_h.pxl */
#define l_h_pxl_size 4
const unsigned char l_h_pxl[4] = {
    0x87, 0x25, 0x29, 0x00
};

/* Contents of file l_i.pxl */
#define l_i_pxl_size 4
const unsigned char l_i_pxl[4] = {
    0x80, 0x21, 0x08, 0x00
};

/* Contents of file l_j.pxl */
#define l_j_pxl_size 4
const unsigned char l_j_pxl[4] = {
    0x20, 0x08, 0x4C, 0x00
};

/* Contents of file l_k.pxl */
#define l_k_pxl_size 4
const unsigned char l_k_pxl[4] = {
    0x85, 0x31, 0x49, 0x00
};

/* Contents of file l_l.pxl */
#define l_l_pxl_size 4
const unsigned char l_l_pxl[4] = {
    0x84, 0x21, 0x04, 0x00
};

/* Contents of file l_m.pxl */
#define l_m_pxl_size 4
const unsigned char l_m_pxl[4] = {
    0x06, 0xAB, 0x5A, 0x80
};

/* Contents of file l_n.pxl */
#define l_n_pxl_size 4
const unsigned char l_n_pxl[4] = {
    0x07, 0x25, 0x29, 0x00
};

/* Contents of file l_o.pxl */
#define l_o_pxl_size 4
const unsigned char l_o_pxl[4] = {
    0x03, 0x25, 0x26, 0x00
};

/* Contents of file l_p.pxl */
#define l_p_pxl_size 4
const unsigned char l_p_pxl[4] = {
    0x03, 0x25, 0xC8, 0x00
};

/* Contents of file l_q.pxl */
#define l_q_pxl_size 4
const unsigned char l_q_pxl[4] = {
    0x03, 0xA4, 0xE1, 0x00
};

/* Contents of file l_r.pxl */
#define l_r_pxl_size 4
const unsigned char l_r_pxl[4] = {
    0x03, 0xA1, 0x08, 0x00
};

/* Contents of file l_s.pxl */
#define l_s_pxl_size 4
const unsigned char l_s_pxl[4] = {
    0x03, 0xB0, 0x6E, 0x00
};

/* Contents of file l_t.pxl */
#define l_t_pxl_size 4
const unsigned char l_t_pxl[4] = {
    0x87, 0x21, 0x06, 0x00
};

/* Contents of file l_u.pxl */
#define l_u_pxl_size 4
const unsigned char l_u_pxl[4] = {
    0x04, 0xA5, 0x27, 0x00
};

/* Contents of file l_v.pxl */
#define l_v_pxl_size 4
const unsigned char l_v_pxl[4] = {
    0x04, 0xA5, 0x44, 0x00
};

/* Contents of file l_w.pxl */
#define l_w_pxl_size 4
const unsigned char l_w_pxl[4] = {
    0x05, 0x6B, 0x55, 0x00
};

/* Contents of file l_x.pxl */
#define l_x_pxl_size 4
const unsigned char l_x_pxl[4] = {
    0x04, 0xA4, 0xC9, 0x00
};

/* Contents of file l_y.pxl */
#define l_y_pxl_size 4
const unsigned char l_y_pxl[4] = {
    0x04, 0x9C, 0x2E, 0x00
};

/* Contents of file l_z.pxl */
#define l_z_pxl_size 4
const unsigned char l_z_pxl[4] = {
    0x07, 0x88, 0x8F, 0x00
};

/* Contents of file null.pxl */
#define null_pxl_size 4
const unsigned char null_pxl[4] = {
    0xFD, 0x77, 0x5F, 0x80
};

/* Contents of file n_0.pxl */
#define n_0_pxl_size 4
const unsigned char n_0_pxl[4] = {
    0x64, 0xA5, 0x26, 0x00
};

/* Contents of file n_1.pxl */
#define n_1_pxl_size 4
const unsigned char n_1_pxl[4] = {
    0x46, 0x10, 0x8E, 0x00
};

/* Contents of file n_2.pxl */
#define n_2_pxl_size 4
const unsigned char n_2_pxl[4] = {
    0x64, 0x88, 0x8F, 0x00
};

/* Contents of file n_3.pxl */
#define n_3_pxl_size 4
const unsigned char n_3_pxl[4] = {
    0xE0, 0x98, 0x2E, 0x00
};

/* Contents of file n_4.pxl */
#define n_4_pxl_size 4
const unsigned char n_4_pxl[4] = {
    0xA5, 0x3C, 0x42, 0x00
};

/* Contents of file n_5.pxl */
#define n_5_pxl_size 4
const unsigned char n_5_pxl[4] = {
    0xF4, 0x38, 0x2E, 0x00
};

/* Contents of file n_6.pxl */
#define n_6_pxl_size 4
const unsigned char n_6_pxl[4] = {
    0x64, 0x39, 0x26, 0x00
};

/* Contents of file n_7.pxl */
#define n_7_pxl_size 4
const unsigned char n_7_pxl[4] = {
    0xF0, 0x88, 0x84, 0x00
};

/* Contents of file n_8.pxl */
#define n_8_pxl_size 4
const unsigned char n_8_pxl[4] = {
    0x64, 0x99, 0x26, 0x00
};

/* Contents of file n_9.pxl */
#define n_9_pxl_size 4
const unsigned char n_9_pxl[4] = {
    0x64, 0x9C, 0x26, 0x00
};

/* Contents of file octo.pxl */
#define octo_pxl_size 4
const unsigned char octo_pxl[4] = {
    0x57, 0xD5, 0xF5, 0x00
};

/* Contents of file parenth_l.pxl */
#define parenth_l_pxl_size 4
const unsigned char parenth_l_pxl[4] = {
    0x44, 0x21, 0x04, 0x00
};

/* Contents of file parenth_r.pxl */
#define parenth_r_pxl_size 4
const unsigned char parenth_r_pxl[4] = {
    0x82, 0x10, 0x88, 0x00
};

/* Contents of file percent.pxl */
#define percent_pxl_size 4
const unsigned char percent_pxl[4] = {
    0xCC, 0x88, 0x99, 0x80
};

/* Contents of file period.pxl */
#define period_pxl_size 4
const unsigned char period_pxl[4] = {
    0x00, 0x00, 0x08, 0x00
};

/* Contents of file pipe.pxl */
#define pipe_pxl_size 4
const unsigned char pipe_pxl[4] = {
    0x84, 0x21, 0x08, 0x00
};

/* Contents of file plus.pxl */
#define plus_pxl_size 4
const unsigned char plus_pxl[4] = {
    0x02, 0x38, 0x80, 0x00
};

/* Contents of file question.pxl */
#define question_pxl_size 4
const unsigned char question_pxl[4] = {
    0x74, 0x4C, 0x02, 0x00
};

/* Contents of file quote.pxl */
#define quote_pxl_size 4
const unsigned char quote_pxl[4] = {
    0xA5, 0x00, 0x00, 0x00
};

/* Contents of file semi.pxl */
#define semi_pxl_size 4
const unsigned char semi_pxl[4] = {
    0x02, 0x00, 0x88, 0x00
};

/* Contents of file slash_b.pxl */
#define slash_b_pxl_size 4
const unsigned char slash_b_pxl[4] = {
    0x82, 0x10, 0x82, 0x00
};

/* Contents of file slash_f.pxl */
#define slash_f_pxl_size 4
const unsigned char slash_f_pxl[4] = {
    0x22, 0x10, 0x88, 0x00
};

/* Contents of file test.pxl */
#define test_pxl_size 4
const unsigned char test_pxl[4] = {
    0xAA, 0xAA, 0xAA, 0x80
};

/* Contents of file under.pxl */
#define under_pxl_size 4
const unsigned char under_pxl[4] = {
    0x00, 0x00, 0x0F, 0x80
};

/* Contents of file u_a.pxl */
#define u_a_pxl_size 4
const unsigned char u_a_pxl[4] = {
    0x74, 0x7F, 0x18, 0x80
};

/* Contents of file u_b.pxl */
#define u_b_pxl_size 4
const unsigned char u_b_pxl[4] = {
    0xF4, 0x7D, 0x1F, 0x00
};

/* Contents of file u_c.pxl */
#define u_c_pxl_size 4
const unsigned char u_c_pxl[4] = {
    0x74, 0x61, 0x17, 0x00
};

/* Contents of file u_d.pxl */
#define u_d_pxl_size 4
const unsigned char u_d_pxl[4] = {
    0xF4, 0x63, 0x1F, 0x00
};

/* Contents of file u_e.pxl */
#define u_e_pxl_size 4
const unsigned char u_e_pxl[4] = {
    0xFC, 0x3F, 0x0F, 0x80
};

/* Contents of file u_f.pxl */
#define u_f_pxl_size 4
const unsigned char u_f_pxl[4] = {
    0xFC, 0x3D, 0x08, 0x00
};

/* Contents of file u_g.pxl */
#define u_g_pxl_size 4
const unsigned char u_g_pxl[4] = {
    0x74, 0x27, 0x17, 0x00
};

/* Contents of file u_h.pxl */
#define u_h_pxl_size 4
const unsigned char u_h_pxl[4] = {
    0x8C, 0x7F, 0x18, 0x80
};

/* Contents of file u_i.pxl */
#define u_i_pxl_size 4
const unsigned char u_i_pxl[4] = {
    0xF9, 0x08, 0x4F, 0x80
};

/* Contents of file u_j.pxl */
#define u_j_pxl_size 4
const unsigned char u_j_pxl[4] = {
    0x78, 0x85, 0x26, 0x00
};

/* Contents of file u_k.pxl */
#define u_k_pxl_size 4
const unsigned char u_k_pxl[4] = {
    0x8C, 0xB9, 0x28, 0x80
};

/* Contents of file u_l.pxl */
#define u_l_pxl_size 4
const unsigned char u_l_pxl[4] = {
    0x84, 0x21, 0x0F, 0x80
};

/* Contents of file u_m.pxl */
#define u_m_pxl_size 4
const unsigned char u_m_pxl[4] = {
    0xDD, 0x6B, 0x18, 0x80
};

/* Contents of file u_n.pxl */
#define u_n_pxl_size 4
const unsigned char u_n_pxl[4] = {
    0x8E, 0x6B, 0x38, 0x80
};

/* Contents of file u_o.pxl */
#define u_o_pxl_size 4
const unsigned char u_o_pxl[4] = {
    0x74, 0x63, 0x17, 0x00
};

/* Contents of file u_p.pxl */
#define u_p_pxl_size 4
const unsigned char u_p_pxl[4] = {
    0xF4, 0x7D, 0x08, 0x00
};

/* Contents of file u_q.pxl */
#define u_q_pxl_size 4
const unsigned char u_q_pxl[4] = {
    0x74, 0x6B, 0x26, 0x80
};

/* Contents of file u_r.pxl */
#define u_r_pxl_size 4
const unsigned char u_r_pxl[4] = {
    0xF4, 0x7D, 0x49, 0x00
};

/* Contents of file u_s.pxl */
#define u_s_pxl_size 4
const unsigned char u_s_pxl[4] = {
    0x7C, 0x1C, 0x1F, 0x00
};

/* Contents of file u_t.pxl */
#define u_t_pxl_size 4
const unsigned char u_t_pxl[4] = {
    0xF9, 0x08, 0x42, 0x00
};

/* Contents of file u_u.pxl */
#define u_u_pxl_size 4
const unsigned char u_u_pxl[4] = {
    0x8C, 0x63, 0x17, 0x00
};

/* Contents of file u_v.pxl */
#define u_v_pxl_size 4
const unsigned char u_v_pxl[4] = {
    0x8C, 0x54, 0xA2, 0x00
};

/* Contents of file u_w.pxl */
#define u_w_pxl_size 4
const unsigned char u_w_pxl[4] = {
    0x8D, 0x6B, 0x55, 0x00
};

/* Contents of file u_x.pxl */
#define u_x_pxl_size 4
const unsigned char u_x_pxl[4] = {
    0x8A, 0x88, 0xA8, 0x80
};

/* Contents of file u_y.pxl */
#define u_y_pxl_size 4
const unsigned char u_y_pxl[4] = {
    0x8A, 0x88, 0x42, 0x00
};

/* Contents of file u_z.pxl */
#define u_z_pxl_size 4
const unsigned char u_z_pxl[4] = {
    0xF8, 0x88, 0x8F, 0x80
};
